import type { Listing, Profile } from './types'

export const mockProfiles: Profile[] = [
  {
    id: '1',
    display_name: 'Sophia',
    bio: 'Looking for genuine connections',
    age: 25,
    location: 'Los Angeles, CA',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop',
    is_verified: true,
    subscription_tier: 'monthly',
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    display_name: 'Emma',
    bio: 'Adventure seeker and coffee lover',
    age: 28,
    location: 'Miami, FL',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop',
    is_verified: true,
    subscription_tier: 'weekly',
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    display_name: 'Olivia',
    bio: 'Music and art enthusiast',
    age: 23,
    location: 'New York, NY',
    avatar_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&h=400&fit=crop',
    is_verified: false,
    subscription_tier: 'free',
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    display_name: 'Ava',
    bio: 'Fitness & wellness coach',
    age: 27,
    location: 'Austin, TX',
    avatar_url: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400&h=400&fit=crop',
    is_verified: true,
    subscription_tier: 'monthly',
    created_at: new Date().toISOString(),
  },
  {
    id: '5',
    display_name: 'Isabella',
    bio: 'Travel photographer',
    age: 26,
    location: 'San Francisco, CA',
    avatar_url: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=400&h=400&fit=crop',
    is_verified: true,
    subscription_tier: 'monthly',
    created_at: new Date().toISOString(),
  },
  {
    id: '6',
    display_name: 'Mia',
    bio: 'Foodie and chef in training',
    age: 24,
    location: 'Chicago, IL',
    avatar_url: 'https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453?w=400&h=400&fit=crop',
    is_verified: false,
    subscription_tier: 'single',
    created_at: new Date().toISOString(),
  },
]

export const mockListings: Listing[] = mockProfiles.map((profile, index) => ({
  id: `listing-${index + 1}`,
  user_id: profile.id,
  title: profile.display_name || 'Anonymous',
  description: profile.bio,
  images: [profile.avatar_url || ''],
  location: profile.location,
  category: 'dating',
  is_featured: profile.is_verified,
  is_active: true,
  expires_at: null,
  views: Math.floor(Math.random() * 500) + 50,
  created_at: new Date().toISOString(),
  profiles: profile,
}))
